# Copyright 2023 Salesforce, Inc. All rights reserved.
version: "3.3"

services:
  local-flex:
    image: docker.repo.local.sfdc.net/sfci/gec/mulesoft-emu/microgateway-policy-engine/microgateway:1.10.4300
    ports:
      - 8081:8081
    volumes:
      - ./config:/usr/local/share/mulesoft/flex-gateway/conf.d/
  backend:
    image: kennethreitz/httpbin
